package consts

var Games []string = []string{
	"Team Fortress 2",
	"Counter-Strike: Global Offensive",
	"PLAYERUNKNOWN'S BATTLEGROUNDS",
	"Unturned",
	"Left 4 Dead 2",
	"PAYDAY 2",
	"Garry's Mod",
	"Warframe",
	"Counter-Strike: Source",
	"Paladins",
	"The Elder Scrolls V: Skyrim",
	"Terraria",
	"Portal 2",
	"Sid Meier's Civilization V",
	"Grand Theft Auto V",
	"Borderlands 2",
	"Robocraft",
	"Rocket League",
	"Portal",
	"War Thunder",
	"Rust",
	"ARK: Survival Evolved",
	"Half-Life 2",
	"Brawlhalla",
	"Chivalry: Medieval Warfare",
	"Trove",
	"Path of Exile",
	"Killing Floor",
	"The Binding of Isaac",
	"No More Room in Hell",
	"Alien Swarm",
	"Warface",
	"Fallout 4",
	"Arma 3",
	"Cities: Skylines",
	"Insurgency",
	"Euro Truck Simulator 2",
	"APB Reloaded",
	"Age of Empires II HD",
	"Dirty Bomb",
	"Dead by Daylight",
	"SMITE",
	"Castle Crashers",
	"The Forest",
	"Tomb Raider",
	"The Witcher 3: Wild Hunt",
	"Wallpaper Engine",
	"Saints Row IV",
	"Call of Duty: Modern Warfare 2",
	"Spiral Knights",
	"Loadout",
	"Black Squad",
	"Counter-Strike Nexon: Zombies",
	"Fallout: New Vegas",
	"Saints Row: The Third",
	"Magicka",
	"Torchlight II",
	"PAYDAY The Heist",
	"Stardew Valley",
	"Evolve Stage 2",
	"Company of Heroes 2",
	"Left 4 Dead",
	"The Witcher 2: Assassins of Kings Enhanced Edition",
	"BioShock Infinite",
	"Arma 2: Operation Arrowhead",
	"Middle-earth: Shadow of Mordor",
	"ORION: Prelude",
	"Day of Defeat: Source",
	"The Elder Scrolls V: Skyrim Special Edition",
	"Clicker Heroes",
	"Starbound",
	"Blacklight: Retribution",
	"Mount & Blade: Warband",
	"Space Engineers",
	"7 Days to Die",
	"Dead Island",
	"Just Cause 2",
	"Magic Duels",
	"Borderlands",
	"Goat Simulator",
	"Life is Strange - Episode 1",
	"Killing Floor 2",
	"theHunter Classic",
	"Half-Life 2: Episode One",
	"Infestation: The New Z",
	"AdVenture Capitalist",
	"Call of Duty: Black Ops",
	"Realm of the Mad God",
	"Dishonored",
	"Sid Meier's Civilization VI",
	"BattleBlock Theater",
	"Undertale",
	"Red Orchestra 2: Heroes of Stalingrad with Rising Storm",
	"Just Survive",
	"Empire: Total War",
	"Dying Light",
	"Fallout Shelter",
	"Total War: ROME II - Emperor Edition",
	"DARK SOULS III",
	"DARK SOULS: Prepare To Die Edition",
	"Half-Life 2: Episode Two",
	"LIMBO",
	"DOOM",
	"Crusader Kings II",
	"Human: Fall Flat",
	"Call of Duty: Black Ops III",
	"America's Army 3",
	"Call of Duty: Black Ops II",
	"Gotham City Impostors Free to Play",
	"Fistful of Frags",
	"Super Meat Boy",
	"Sniper Elite V2",
	"A.V.A. Alliance of Valiant Arms",
	"Subnautica",
	"DC Universe Online",
	"Prison Architect",
	"The Walking Dead",
	"This War of Mine",
	"Outlast",
	"Hitman: Absolution",
	"Trine 2: Complete Story",
	"The Binding of Isaac: Rebirth",
	"SpeedRunners",
	"Ace of Spades: Battle Builder",
	"Dungeon Defenders II",
	"Just Cause 2: Multiplayer Mod",
	"Amnesia: The Dark Descent",
	"Sid Meier's Civilization: Beyond Earth",
	"Deceit",
	"Sanctum 2",
	"Hotline Miami",
	"Bastion",
	"Zombie Panic! Source",
	"South Park: The Stick of Truth",
	"Warhammer 40,000: Dawn of War II",
	"Rise of the Tomb Raider",
	"Dustforce DX",
	"Dungeon Defenders",
	"Batman: Arkham City - Game of the Year Edition",
	"Block N Load",
	"Guns of Icarus Online",
	"Viscera Cleanup Detail: Shadow Warrior",
	"Toribash",
	"World of Guns: Gun Disassembly",
	"Dino D-Day",
	"Just Cause 3",
	"Survarium",
	"Mafia II",
	"Papers, Please",
	"Dead Island Riptide",
	"Tabletop Simulator",
	"ARK: Survival Of The Fittest",
	"Golf With Your Friends",
	"Batman: Arkham Asylum Game of the Year Edition",
	"XCOM 2",
	"Darkest Dungeon",
	"Napoleon: Total War",
	"Borderlands: The Pre-Sequel",
	"Monaco: What's Yours Is Mine",
	"How to Survive 2",
	"Banished",
	"Fallen Earth Free2Play",
	"Sanctum",
	"Total War: WARHAMMER",
	"Transformice",
	"Codename CURE",
	"Serious Sam 3: BFE",
	"Metro 2033 Redux",
	"Stick Fight: The Game",
	"Plague Inc: Evolved",
	"Tropico 4",
	"Natural Selection 2",
	"Europa Universalis IV",
	"Stellaris",
	"Star Conflict",
	"Gear Up",
	"POSTAL 2",
	"GunZ 2: The Second Duel",
	"ArcheBlade",
	"Surgeon Simulator",
	"The Long Dark",
	"Broforce",
	"Depth",
	"Line of Sight",
	"Source Filmmaker",
	"Batman: Arkham Origins",
	"Warhammer: End Times - Vermintide",
	"Risk of Rain",
	"AirMech Strike",
	"America's Army: Proving Grounds",
	"Wolfenstein: The New Order",
	"Sniper Elite 3",
	"Alan Wake",
	"Alien Swarm: Reactive Drop",
	"Mad Max",
	"METAL GEAR SOLID V: THE PHANTOM PAIN",
	"Max Payne 3",
	"Cuphead",
	"Worms Revolution",
	"Crossout",
	"Tropico 5",
	"Factorio",
	"BRINK",
	"Game Dev Tycoon",
	"Champions Online",
	"Gang Beasts",
	"Emily is Away",
	"Divinity: Original Sin 2",
	"Darksiders",
	"Planet Coaster",
	"Shadow Warrior",
	"Plants vs. Zombies GOTY Edition",
	"Car Mechanic Simulator 2015",
	"Skullgirls",
	"Contagion",
	"Assassin's Creed IV Black Flag",
	"Trine Enchanted Edition",
	"Squad",
	"L.A. Noire",
	"AudioSurf",
	"Mark of the Ninja",
	"BioShock 2",
	"Endless Space - Collection",
	"HITMAN",
	"ShellShock Live",
	"STAR WARS Knights of the Old Republic II - The Sith Lords",
	"Endless Legend",
	"SEGA Mega Drive and Genesis Classics",
	"How to Survive",
	"Hero Siege",
	"Divinity: Original Sin - Enhanced Edition",
	"GRID 2",
	"Metro: Last Light Redux",
	"Fractured Space",
	"SNOW",
	"Rogue Legacy",
	"Grim Dawn",
	"Yu-Gi-Oh! Duel Links",
	"Business Tour - Online Multiplayer Board Game",
	"Mortal Kombat X",
	"DARK SOULS II: Scholar of the First Sin",
	"Quake Live",
	"Sleeping Dogs",
	"Call of Duty: Ghosts",
	"Black Desert Online",
	"Bloons TD Battles",
	"Batman: Arkham Knight",
	"No Man's Sky",
	"SPINTIRES",
	"Age of Mythology: Extended Edition",
	"Deus Ex: Human Revolution - Director's Cut",
	"Hearts of Iron IV",
	"Total War: ATTILA",
	"Transistor",
	"Altitude",
	"Geometry Dash",
	"Resident Evil 6 / Biohazard 6",
	"Thief",
	"Ultra Street Fighter IV",
	"Who's Your Daddy",
	"The Escapists",
	"Scribblenauts Unlimited",
	"Double Action: Boogaloo",
	"BioShock Remastered",
	"Worms Reloaded",
	"Warhammer 40,000: Dawn of War II Chaos Rising",
	"Injustice: Gods Among Us Ultimate Edition",
	"FEZ",
	"Pillars of Eternity",
	"DARK SOULS II",
	"Warhammer: Vermintide 2",
	"Brutal Legend",
	"Sonic & All-Stars Racing Transformed Collection",
	"Mount & Blade: With Fire & Sword",
	"Aliens vs. Predator",
	"Slime Rancher",
	"Yet Another Zombie Defense",
	"Divinity: Original Sin (Classic)",
	"Psychonauts",
	"Layers of Fear",
	"Hand Simulator",
	"Mortal Kombat Komplete Edition",
	"Duck Game",
	"Homefront",
	"NieR:Automata",
	"Deus Ex: Mankind Divided",
	"Iron Snout",
	"Stranded Deep",
	"Verdun",
	"Quake Champions",
	"The Darkness II",
	"Enter the Gungeon",
	"Conan Exiles",
	"Interstellar Marines",
	"FINAL FANTASY VII",
	"Dishonored 2",
	"Call of Duty: Advanced Warfare - Gold Edition",
	"Miscreated",
	"Crypt of the NecroDancer",
	"Slay the Spire",
	"Kingdom: Classic",
	"Orcs Must Die! Unchained",
	"Planetary Annihilation",
	"Lead and Gold: Gangs of the Wild West",
	"Orcs Must Die!",
	"PAC-MAN Championship Edition DX+",
	"Warhammer 40,000: Space Marine",
	"Everlasting Summer",
	"F.E.A.R. 3",
	"Sins of a Solar Empire: Rebellion",
	"Sniper: Ghost Warrior 2",
	"To the Moon",
	"State of Decay",
	"Dungeon of the Endless",
	"Pirates, Vikings, and Knights II",
	"DiRT Rally",
	"Frozen Synapse",
	"Brothers - A Tale of Two Sons",
	"The Walking Dead: Season 2",
	"Day of Infamy",
	"Supreme Commander 2",
	"Super Hexagon",
	"Titan Quest Anniversary Edition",
	"Hotline Miami 2: Wrong Number",
	"WAKFU",
	"Assassin's Creed Origins",
	"Serious Sam HD: The First Encounter",
	"F1 2015",
	"Jotun: Valhalla Edition",
	"Men of War: Assault Squad 2",
	"World of Warships",
	"Braid",
	"The Wolf Among Us",
	"Red Faction Guerrilla Steam Edition",
	"Resident Evil 5/ Biohazard 5",
	"Gauntlet Slayer Edition",
	"Hollow Knight",
	"Ori and the Blind Forest",
	"LEGO Marvel Super Heroes",
	"DmC: Devil May Cry",
	"World of Goo",
	"Ryse: Son of Rome",
	"Project CARS",
	"SCP: Secret Laboratory",
	"HELLDIVERS",
	"Dragon's Dogma: Dark Arisen",
	"NARUTO SHIPPUDEN: Ultimate Ninja STORM 4",
	"Kingdoms of Amalur: Reckoning",
	"Firewatch",
	"Hammerwatch",
	"Total War: WARHAMMER II",
	"Football Manager 2018",
	"Move or Die",
	"Rising Storm 2: Vietnam",
	"Poker Night at the Inventory",
	"Middle-earth: Shadow of War",
	"Getting Over It with Bennett Foddy",
	"Magic 2014 - Duels of the Planeswalkers",
	"Dust: An Elysian Tail",
	"Mount Your Friends",
	"Zombie Army Trilogy",
	"8BitMMO",
	"Sniper: Ghost Warrior",
	"Zula Europe",
	"Sleeping Dogs: Definitive Edition",
	"The Talos Principle",
	"Farming Simulator 15",
	"Portal Knights",
	"Spelunky",
	"Unreal Tournament 3 Black",
	"Reus",
	"Call of Duty: WWII",
	"METAL GEAR SOLID V: GROUND ZEROES",
	"Duke Nukem Forever",
	"Strife",
	"Relic Hunters Zero",
	"Nation Red",
	"Hacknet",
	"Dragons and Titans",
	"Call of Duty: Infinite Warfare",
	"Lost Castle",
	"BRAIN / OUT",
	"Rise of Nations: Extended Edition",
	"Magicka 2",
	"WildStar",
	"HuniePop",
	"Mafia III",
	"Red Orchestra: Ostfront 41-45",
	"Town of Salem",
	"The Culling",
	"SUPERHOT",
	"Blood and Bacon",
	"Cortex Command",
	"Worms Clan Wars",
	"Keep Talking and Nobody Explodes",
	"Dead Cells",
	"Stronghold Crusader 2",
	"Kingdom Come: Deliverance",
	"Time Clickers",
	"Assetto Corsa",
	"DRAGON BALL XENOVERSE",
	"theHunter: Call of the Wild",
	"Raft",
	"We Were Here",
	"Poly Bridge",
	"BeamNG.drive",
	"Farming Simulator 17",
	"Deadlight",
	"Zero Gear",
	"Nidhogg",
	"Northgard",
	"MechWarrior Online Solaris 7",
	"Red Faction: Armageddon",
	"School of Dragons",
	"CS2D",
	"MOBIUS FINAL FANTASY",
	"BrainBread 2",
	"Ultimate Chicken Horse",
	"E.Y.E: Divine Cybermancy",
	"Valkyria Chronicles",
	"Ori and the Blind Forest: Definitive Edition",
	"Age of Wonders III",
	"VVVVVV",
	"Legend of Grimrock",
	"They Are Billions",
	"Defy Gravity Extended",
	"Space Pirates and Zombies",
	"LEGO Worlds",
	"Universe Sandbox",
	"Endless Space 2",
	"The Banner Saga",
	"Baldur's Gate: Enhanced Edition",
	"Deponia",
	"Lords Of The Fallen",
	"SUNLESS SEA",
	"The Evil Within",
	"Primal Carnage",
	"EVGA Precision XOC",
	"Homeworld Remastered Collection",
	"The Incredible Adventures of Van Helsing",
	"Bendy and the Ink Machine",
	"Dwarfs - F2P",
	"Sniper Elite 4",
	"Youtubers Life",
	"Lethal League",
	"Risen 2: Dark Waters",
	"DEFCON",
	"Monday Night Combat",
	"Atlas Reactor",
	"FINAL FANTASY XIII",
	"resident evil 4 / biohazard 4",
	"Prey",
	"Two Worlds II HD",
	"Gunpoint",
	"Viscera Cleanup Detail",
	"METAL GEAR RISING: REVENGEANCE",
	"Fallout: New Vegas",
	"Democracy 3",
	"Card Hunter",
	"SpaceChem",
	"Warhammer 40,000: Dawn of War III",
	"Frostpunk",
	"LawBreakers",
	"One Finger Death Punch",
	"NARUTO SHIPPUDEN: Ultimate Ninja STORM 3 Full Burst HD",
	"Poker Night 2",
	"Boring Man - Online Tactical Stickman Combat",
	"INSIDE",
	"The Red Solstice",
	"RESIDENT EVIL 7 biohazard / BIOHAZARD 7 resident evil",
	"Steel Ocean",
	"Stories: The Path of Destinies",
	"Resident Evil Revelations 2 / Biohazard Revelations 2",
	"Minion Masters",
	"METAL SLUG 3",
	"Sonic Generations Collection",
	"BIT.TRIP RUNNER",
	"Outland",
	"Nuclear Dawn",
	"Dungeon Siege III",
	"Rock of Ages",
	"The Descendant",
	"Friday the 13th: The Game",
	"Dead Rising 2",
	"Wasteland 2: Director's Cut",
	"Painkiller Hell & Damnation",
	"Transmissions: Element 120",
	"Hand of Fate",
	"Wargame: European Escalation",
	"Pixel Piracy",
	"Race The Sun",
	"Only If",
	"Blade Symphony",
	"Machinarium",
	"Doom 3: BFG Edition",
	"FORCED: Slightly Better Edition",
	"Woodle Tree Adventures",
	"Beat Hazard",
	"Talisman: Digital Edition",
	"Homefront: The Revolution",
	"Wolfenstein: The Old Blood",
	"Overcooked",
	"Game of Thrones - A Telltale Games Series",
	"Lucius",
	"Darksiders Warmastered Edition",
	"Black Mesa",
	"Eador. Masters of the Broken World",
	"Hyper Light Drifter",
	"Modern Combat Versus",
	"Satellite Reign",
	"Tales from the Borderlands",
	"Heroes of Might & Magic III - HD Edition",
	"Farming Simulator 2013 Titanium Edition",
	"Cave Story+",
	"FaceRig",
	"Viridi",
	"Remember Me",
	"Guns and Robots",
	"Starpoint Gemini 2",
	"Dungeons 2",
	"Shovel Knight: Treasure Trove",
	"GRID Autosport",
	"Fable Anniversary",
	"LEGO The Lord of the Rings",
	"Thomas Was Alone",
	"FINAL FANTASY VIII",
	"Octodad: Dadliest Catch",
	"I am Bread",
	"60 Seconds!",
	"NEKOPARA Vol. 1",
	"ABZU",
	"Sniper Elite: Nazi Zombie Army",
	"TOXIKK",
	"Planetary Annihilation: TITANS",
	"FINAL FANTASY X/X-2 HD Remaster",
	"Fortified",
	"Anomaly: Warzone Earth",
	"Armello",
	"NEKOPARA Vol. 0",
	"Kingdoms and Castles",
	"Tyranny",
	"The Flame in the Flood",
	"Darksiders II Deathinitive Edition",
	"Defense Grid: The Awakening",
	"Pinball Arcade",
	"Viscera Cleanup Detail: Santa's Rampage",
	"Amnesia: A Machine for Pigs",
	"Dungeons of Dredmor",
	"BlackShot: Mercenary Warfare FPS",
	"Soldier Front 2",
	"Lara Croft and the Guardian of Light",
	"Wolfenstein II: The New Colossus",
	"Door Kickers",
	"Mini Metro",
	"Killer is Dead - Nightmare Edition",
	"Blackwake",
	"TEKKEN 7",
	"Punch Club",
	"Duelyst",
	"Gone Home",
	"Guacamelee! Gold Edition",
	"NBA 2K18",
	"Golf It!",
	"Saints Row: Gat out of Hell",
	"Crush Crush",
	"DRAGON BALL XENOVERSE 2",
	"Turbo Pug DX",
	"Life is Feudal: Your Own",
	"Jet Set Radio",
	"Dungeon Fighter Online",
	"Shadowrun: Dragonfall - Director's Cut",
	"You Have to Win the Game",
	"Ace Combat Assault Horizon - Enhanced Edition",
	"Out There Somewhere",
	"Alan Wake's American Nightmare",
	"Grim Fandango Remastered",
	"3DMark",
	"Murdered: Soul Suspect",
	"Craft The World",
	"Kingdom: New Lands",
	"Bold New World",
	"Resident Evil Revelations / Biohazard Revelations",
	"Warhammer 40,000: Eternal Crusade",
	"NBA 2K17",
	"Offworld Trading Company",
	"Blockstorm",
	"100% Orange Juice",
	"Soda Dungeon",
	"Learn to Fly 3",
	"Reigns",
	"The Witness",
	"Nuclear Throne",
	"Battleborn",
	"Car Mechanic Simulator 2018",
	"SOMA",
	"TerraTech",
	"FINAL FANTASY XV WINDOWS EDITION",
	"The Escapists 2",
	"Of Guards And Thieves",
	"Worms Ultimate Mayhem",
	"Realm Grinder",
	"Styx: Master of Shadows",
	"Sniper Elite: Nazi Zombie Army 2",
	"The Swapper",
	"Forts",
	"X3: Terran Conflict",
	"Jurassic World Evolution",
	"Governor of Poker 3",
	"Bad Rats: the Rats' Revenge",
	"Galactic Civilizations III",
	"NBA 2K16",
	"Puzzle Pirates",
	"RUNNING WITH RIFLES",
	"Life is Strange: Before the Storm",
	"Pixel Puzzles Ultimate",
	"Mirror",
	"Aliens: Colonial Marines Collection",
	"THE KING OF FIGHTERS XIII STEAM EDITION",
	"GUNS UP!",
	"Victor Vran ARPG",
	"Teleglitch: Die More Edition",
	"Turmoil",
	"Magic: The Gathering - Duels of the Planeswalkers 2013",
	"CastleMiner Z",
	"Cities in Motion 2",
	"Prismata",
	"Kane & Lynch 2: Dog Days",
	"UnEpic",
	"ibb & obb",
	"Batla",
	"DRAGON BALL FighterZ",
	"Superbrothers: Sword & Sworcery EP",
	"ICEY",
	"Call to Arms",
	"Ball 3D: Soccer Online",
	"A Story About My Uncle",
	"Terra Incognita ~ Chapter One: The Descendant",
	"Written in the Sky",
	"Evoland",
	"Piercing Blow",
	"DLC Quest",
	"Bayonetta",
	"Hellblade: Senua's Sacrifice",
	"Murder Miners",
	"Friday the 13th: Killer Puzzle",
	"Baldur's Gate II: Enhanced Edition",
	"Broken Age",
	"My Summer Car",
	"Construction Simulator 2015",
	"Sonic Adventure 2",
	"Hell Yeah! Wrath of the Dead Rabbit",
	"Resident Evil / biohazard HD REMASTER",
	"Heaven Island - VR MMO",
	"Osmos",
	"Jamestown",
	"Loading Screen Simulator",
	"Freebie",
	"Dystopia",
	"Tales of Zestiria",
	"Men of War: Assault Squad",
	"Turn Around",
	"Shadow Tactics: Blades of the Shogun",
	"Hyperdimension Neptunia Re;Birth",
	"Sol Survivor",
	"Nexuiz",
	"Skyforge",
	"State of Decay: YOSE",
	"Time of Dragons",
	"Turbo Dismount",
	"Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad",
	"Salt and Sanctuary",
	"LEGO The Hobbit",
	"Savage Lands",
	"Robot Roller-Derby Disco Dodgeball",
	"The Culling Of The Cows",
	"Back to Bed",
	"Tower Wars",
	"Invisible, Inc.",
	"Trine 3: The Artifacts of Power",
	"Polarity",
	"SAMOLIOTIK",
	"Outlast 2",
	"Dr. Langeskov, The Tiger, and The Terribly Cursed Emerald: A Whirlwind Heist",
	"RWBY: Grimm Eclipse",
	"F1 2017",
	"Cook, Serve, Delicious!",
	"DEAD OR ALIVE 5 Last Round: Core Fighters",
	"Hide and Shriek",
	"Bloody Trapland",
	"Crusaders of the Lost Idols",
	"The Vanishing of Ethan Carter",
	"Castlevania: Lords of Shadow - Ultimate Edition",
	"Rebel Galaxy",
	"Cogs",
	"Magic: The Gathering - Duels of the Planeswalkers 2012",
	"This Is the Police",
	"Genital Jousting",
	"Mountain",
	"Nomad",
	"Revolution Ace",
	"AI War: Fleet Command",
	"Streets of Rogue",
	"Never Alone (Kisima Ingitchuna)",
	"Death Rally",
	"Long Live The Queen",
	"Planet Explorers",
	"Clustertruck",
	"RPG MO",
	"Party Hard",
	"SteamWorld Dig",
	"Princess.Loot.Pixel.Again",
	"Grey Goo",
	"DYNASTY WARRIORS 8: Xtreme Legends Complete Edition / çœŸãƒ»ä¸‰åœ‹ç„¡å\x8FŒï¼— with çŒ›å°†ä¼\x9D",
	"NARUTO SHIPPUDEN: Ultimate Ninja STORM Revolution",
	"F1 2012",
	"War for the Overworld",
	"Galactic Junk League",
	"Planetbase",
	"Cossacks 3",
	"No Time To Explain Remastered",
	"Tiny and Big: Grandpa's Leftovers",
	"Organ Trail: Director's Cut",
	"Kingdom Wars",
	"The Last Hope",
	"VEGA Conflict",
	"BIT.TRIP Presents... Runner2: Future Legend of Rhythm Alien",
	"Windward",
	"Really Big Sky",
	"Anarchy Arcade",
	"Slender: The Arrival",
	"Bloons TD 5",
	"Halo: Spartan Assault",
	"Timberman",
	"Toki Tori",
	"House Flipper",
	"Sniper Fury",
	"Titan Souls",
	"Morphopolis",
	"Catch a Falling Star",
	"DARK SOULS: REMASTERED",
	"King Arthur's Gold",
	"Nioh: Complete Edition",
	"Minecraft: Story Mode - A Telltale Games Series",
	"Guild Quest",
	"The Banner Saga: Factions",
	"One Piece Pirate Warriors 3",
	"LEGO Jurassic World",
	"X Rebirth",
	"Risen 3 - Titan Lords",
	"The Tower Of Elements",
	"Knights of Pen and Paper +1 Edition",
	"Costume Quest",
	"DETOUR",
	"Revenge of the Titans",
	"State of Anarchy",
	"Solar 2",
	"Battle Islands",
	"Transport Fever",
	"SAS: Zombie Assault 4",
	"Damned",
	"Space Beret",
	"The LEGO Movie - Videogame",
	"Giana Sisters: Twisted Dreams",
	"Dead Island Definitive Edition",
	"Hard Reset Extended Edition",
	"Pony Island",
	"FINAL FANTASY IX",
	"Mordheim: City of the Damned",
	"AX:EL - Air XenoDawn",
	"Epigenesis",
	"Dead Realm",
	"Botanicula",
	"Grow Home",
	"Motorsport Manager",
	"LEGO Batman3: Beyond Gotham",
	"Squishy the Suicidal Pig",
	"Data Hacker: Reboot",
	"The Room",
	"Simply Chess",
	"MANDAGON",
	"Escape This",
	"Planets Under Attack",
	"Supraball",
	"Eternal Card Game",
	"Dead Maze",
	"Audiosurf 2",
	"Ratz Instagib",
	"And Yet It Moves",
	"Trashville",
	"Invasion: Brain Craving",
	"God Mode",
	"Battlefleet Gothic: Armada",
	"The Bridge",
	"The Hat Man: Shadow Ward",
	"Zeno Clash",
	"South Park: The Fractured But Whole",
	"HunieCam Studio",
	"The Jackbox Party Pack 3",
	"Gems of War - Puzzle RPG",
	"Spintires: MudRunner",
	"F1 2016",
	"NEKOPARA Vol. 2",
	"Elements: Soul of Fire",
	"Mortal Online",
	"Atom Zombie Smasher",
	"Rec Room",
	"One Way Heroics",
	"SimplePlanes",
	"LUFTRAUSERS",
	"Pool Nation FX Lite",
	"Tricky Towers",
	"Shank",
	"Star Chronicles: Delta Quadrant",
	"Atonement: Scourge of Time",
	"Yellow: The Yellow Artifact",
	"Project Starship",
	"Insanity Clicker",
	"Half Minute Hero: Super Mega Neo Climax Ultimate Boy",
	"Might & Magic: Clash of Heroes",
	"Abyss Odyssey",
	"Dungeon of Zolthan",
	"MX vs. ATV Reflex",
	"Mercenary Kings: Reloaded Edition",
	"The Jackbox Party Pack",
	"Dream Daddy: A Dad Dating Simulator",
	"Make it indie!",
	"Binary Domain",
	"Blackguards",
	"Her Story",
	"METRO CONFLICT: THE ORIGIN",
	"Magic 2015 - Duels of the Planeswalkers",
	"Viking: Battle for Asgard",
	"Tooth and Tail",
	"City of Chains",
	"Stronghold 2: Steam Edition",
	"Kingdom Rush",
	"The Jackbox Party Pack 2",
	"Devil May Cry 4 Special Edition",
	"Serious Sam Fusion 2017 (beta)",
	"LYNE",
	"LISA",
	"Renegade Ops",
	"The District",
	"Star Saviors",
	"Pit People",
	"Dark and Light",
	"Bejeweled 3",
	"Ticket to Ride",
	"There's Poop In My Soup",
	"Blood Bowl 2",
	"Elements II: Hearts of Light",
	"STRIDER / ã‚¹ãƒˆãƒ©ã‚¤ãƒ€ãƒ¼é£›ç«œ",
	"Sonic Adventure DX",
	"VA-11 Hall-A: Cyberpunk Bartender Action",
	"EVERSPACE",
	"Street Warriors Online",
	"BATTLETECH",
	"Tricolour Lovestory",
	"Montaro",
	"Monkey Island 2 Special Edition: LeChuck's Revenge",
	"Aragami",
	"Downwell",
	"Outrage",
	"Rocketbirds: Hardboiled Chicken",
	"Worms W.M.D",
	"Drayt Empire",
	"Rivals of Aether",
	"For The King",
	"Space Farmers",
	"Turbo Pug 3D",
	"Tales of Berseria",
	"Missing Translation",
	"Fall of Civilization",
	"Hatoful Boyfriend",
	"Half Dead",
	"Dungetris",
	"Incitement 3",
	"Madballs in Babo:Invasion",
	"Oxenfree",
	"Retro City Rampage DX",
	"Little Nightmares",
	"HellAngel",
	"Stigmat",
	"LOST PLANET 3",
	"PIGMENTUM",
	"Pid",
	"Shadow Warrior Classic Redux",
	"The Walking Dead: A New Frontier",
	"Atonement 2: Ruptured by Despair",
	"Domina",
	"Guardians of Orion",
	"Omerta - City of Gangsters",
	"Castle Story",
	"Trouble In The Manor",
	"Nuclear Contingency",
	"Rise of the Triad",
	"CPUCores :: Maximize Your FPS",
	"Batman - The Telltale Series",
	"Cat Goes Platform",
	"Game of Thrones",
	"The Cave",
	"DiRT 4",
	"Trolley Gold",
	"Rock of Ages 2: Bigger & Boulder",
	"Shadowrun: Hong Kong - Extended Edition",
	"Orbital Gear",
	"Desolate Wastes: Vendor Chronicles",
	"Germ Wars",
	"hack_me",
	"BIT.TRIP BEAT",
	"Home Behind",
	"METAL SLUG DEFENSE",
	"Divinity: Dragon Commander",
	"Fluffy Creatures VS The World",
	"Day of the Tentacle Remastered",
	"Project CARS 2",
	"Camera Obscura",
	"Take Thy Throne",
	"Road Madness",
	"Tabletopia",
	"Dead Rising 2: Off the Record",
	"Bit Blaster XL",
	"Stealth Inc 2: A Game of Clones",
	"Unalive",
	"Wizard of Legend",
	"Next Day: Survival",
	"Legend of Grimrock 2",
	"Deep Space Dash",
	"OLDTV",
	"Grind Zones",
	"Labyronia RPG",
	"POSTAL",
	"Hyper color ball",
	"Age of Conquest IV",
	"Rampage Knights",
	"Battle Royale Trainer",
	"Final Quest II",
	"Greyfox RPG",
	"The Four Kings Casino and Slots",
	"PixARK",
	"DuckTales: Remastered",
	"Pool Nation",
	"Shatter",
	"The Incredible Adventures of Van Helsing II",
	"ELEX",
	"Legend of Mysteria RPG",
	"The Legend of Heroes: Trails in the Sky",
	"Blood Bowl: Chaos Edition",
	"Grand Pigeon's Duty",
	"Deadfall Adventures",
	"Owlboy",
	"Pixel Puzzles: Japan",
	"Streamline",
	"Chaos on Deponia",
	"My Time At Portia",
	"Spikit",
	"Run Away",
	"Stronghold Legends: Steam Edition",
	"SOS",
	"RUSH",
	"Stacking",
	"Prominence Poker",
	"Bridge Constructor",
	"Idle Champions of the Forgotten Realms",
	"Momodora: Reverie Under The Moonlight",
	"The Basement Collection",
	"Project Highrise",
	"Drop Alive",
	"Capsized",
	"LEGO STAR WARS: The Force Awakens",
	"FINAL FANTASY XIII-2",
	"Detention",
	"RADical ROACH Remastered",
	"The Land of Dasthir",
	"Reset 1-1",
	"The Typing of The Dead: Overkill",
	"Under Zero",
	"Master of Orion",
	"GOD EATER 2 Rage Burst",
	"Sleeping Valley",
	"Warriors of Vilvatikta",
	"ENSLAVED: Odyssey to the West Premium Edition",
	"Ziggurat",
	"Minimum",
	"Iron Sky: Invasion",
	"Gunscape",
	"Crawl",
	"Sonic CD",
	"Royal Quest",
	"Hatred",
	"Shelter 2",
	"Shake Your Money Simulator 2016",
	"Data Hacker: Initiation",
	"HOARD",
	"Jazzpunk: Director's Cut",
	"Energy Cycle",
	"Mad Hunter",
	"Jet Racing Extreme: The First Encounter",
	"Cities in Motion",
	"SolForge",
}

var TopListLengths []int = []int{
	1,
	3,
	5,
	10,
}
